# Site settings
title: Art4ur
email: arthur@premazon.com
description: > # this means to ignore newlines until "baseurl:"
  I am a tech at <a href="http://www.premazon.com">Premazon</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://art4ur.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  art4ur

# Build settings
markdown: kramdown
